package com.riskscanner.dependencyriskanalyzer.service.ai;

import com.riskscanner.dependencyriskanalyzer.dto.DependencyEnrichmentDto;
import com.riskscanner.dependencyriskanalyzer.model.DependencyCoordinate;

/**
 * Service for generating AI-powered explanations and summaries for dependency risk.
 *
 * <p>AI is used only for interpretive tasks:
 * <ul>
 *   <li>Natural language explanations of risk factors</li>
 *   <li>Summarization of vulnerability and maintenance data</li>
 *   <li>Prioritization recommendations</li>
 * </ul>
 *
 * <p>Implementations must provide fallback behavior when AI is unavailable.
 */
public interface AIExplanationService {

    /**
     * Generates a natural language explanation and recommendations for a dependency's risk.
     *
     * @param dependency the dependency to explain
     * @param enrichment enrichment data (vulnerabilities, GitHub stats, etc.)
     * @param deterministicRiskLevel pre-calculated risk level from deterministic analysis
     * @param deterministicRiskScore pre-calculated risk score from deterministic analysis
     * @return explanation result with text and recommendations; never null
     */
    ExplanationResult explainRisk(
            DependencyCoordinate dependency,
            DependencyEnrichmentDto enrichment,
            String deterministicRiskLevel,
            Integer deterministicRiskScore
    );

    /**
     * Tests whether the AI service is available and configured.
     *
     * @return true if AI is available; false if fallback will be used
     */
    boolean isAvailable();

    /**
     * Result of an AI explanation, always providing fallback values.
     *
     * @param explanation natural language explanation (never null)
     * @param recommendations list of recommendations (never null, may be empty)
     * @param fromAI true if generated by AI; false if fallback template was used
     */
    record ExplanationResult(
            String explanation,
            java.util.List<String> recommendations,
            boolean fromAI
    ) {}
}
